version: '3.8'

services:
  taskmanagement_db:
    image: khaledhf/task-db:latest
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
      MYSQL_DATABASE: "taskmanagement"
  taskmanagement_app:
    image: khaledhf/taskmanagement-main:latest
    ports:
      - "9222:9222"
    depends_on:
      - taskmanagement_db
